   # hapPyness: Project One 
 Team Boa 
       (Aashita, 
       Alannah,
       Ben,
       and Brian)

Charles Schulz once said that “happiness is a warm puppy”. According to Walt Disney, “happiness is a state of mind” and author, Tom Bodett, offered that "a person needs just three things to be truly happy in this world: Someone to love, something to do, and something to hope for.” For many, happiness is hard to quantify. However, in 2012 the first World Happiness Report was published based on Gallup poll data. This report uses six factors to measure happiness: economic production, social support, life expectancy, freedom, absence of corruption, and generosity. (Tom may have been on to something.)

Our team will be analyzing this data to determine correlations between metrics (such as the relationship between GDP per capita and the happiness index, and life expectancy vs freedom) and across years. We will also focus on the position of the United States on the list, seeing just how we measure up to the happiest and uphappiest nations to start, then going on to further analyze the metrics to see what story they tell. It will also be interesting to see how 2020 measures up to years prior, considering the Covid-19 pandemic, widespread social unrest, and the general consensus that it was a terrible year.

In [43]:
# Import dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import linregress

In [44]:
# Store csv file paths in variables
path_2016 = "../Resources/clean_data_2016.csv"
path_2017 = "../Resources/clean_data_2017.csv"
path_2018 = "../Resources/clean_data_2018.csv"
path_2019 = "../Resources/clean_data_2019.csv"
path_2020 = "../Resources/clean_data_2020.csv"

In [45]:
clean_data_2016_df = pd.read_csv(path_2016)
clean_data_2017_df = pd.read_csv(path_2017)
clean_data_2018_df = pd.read_csv(path_2018)
clean_data_2019_df = pd.read_csv(path_2019)
clean_data_2020_df = pd.read_csv(path_2020)

In [46]:
frames = [clean_data_2016_df, clean_data_2017_df, clean_data_2018_df, clean_data_2019_df, clean_data_2020_df]

all_years_df = pd.concat(frames)

In [52]:
all_years_df["Country"].value_counts().tail(50)

Canada                       5
New Zealand                  5
Honduras                     5
Costa Rica                   5
Iceland                      5
India                        5
Madagascar                   5
Zambia                       5
Morocco                      5
Croatia                      5
Germany                      5
Malawi                       5
Nepal                        5
Uruguay                      5
Moldova                      5
Belarus                      5
Mexico                       5
Kenya                        5
Chile                        5
Armenia                      5
Switzerland                  5
Lesotho                      4
Laos                         4
Syria                        4
Bhutan                       4
Qatar                        4
Mozambique                   4
Macedonia                    4
Central African Republic     4
Somalia                      4
Angola                       3
North Cyprus                 3
Belize                       3
Sudan                        3
Taiwan                       3
Comoros                      3
Hong Kong                    3
Trinidad and Tobago          3
Swaziland                    2
Trinidad & Tobago            2
Northern Cyprus              2
Taiwan Province of China     2
Gambia                       2
North Macedonia              1
Hong Kong S.A.R., China      1
Suriname                     1
Hong Kong S.A.R. of China    1
Somaliland Region            1
Puerto Rico                  1
Maldives                     1
Name: Country, dtype: int64

In [53]:
all_years_df["Country"] = all_years_df["Country"].str.replace("Trinidad & Tobago", "Trinidad and Tobago")

In [79]:
all_years_df

,Unnamed: 0,Country,Happiness Score,GDP per Capita,Social Support,Health/Life Expectancy,Freedom to Make Choices,Generosity,Perceptions of Gov’t Corruption,Year
0,0,Denmark,7.5260,1.441780,1.163740,0.795040,0.579410,0.361710,0.444530,2016
1,1,Switzerland,7.5090,1.527330,1.145240,0.863030,0.585570,0.280830,0.412030,2016
2,2,Iceland,7.5010,1.426660,1.183260,0.867330,0.566240,0.476780,0.149750,2016
3,3,Norway,7.4980,1.577440,1.126900,0.795790,0.596090,0.378950,0.357760,2016
4,4,Finland,7.4130,1.405980,1.134640,0.810910,0.571040,0.254920,0.410040,2016
...,...,...,...,...,...,...,...,...,...,...
148,148,Central African Republic,3.4759,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,2020
149,149,Rwanda,3.3123,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,2020
150,150,Zimbabwe,3.2992,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,2020
151,151,South Sudan,2.8166,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,2020
152,152,Afghanistan,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,2020

In [70]:
all_years_df["Country"].value_counts()

Ethiopia                     5
Myanmar                      5
Iran                         5
Estonia                      5
Slovakia                     5
                            ..
Suriname                     1
Hong Kong S.A.R. of China    1
Somaliland Region            1
Puerto Rico                  1
Maldives                     1
Name: Country, Length: 168, dtype: int64

In [87]:
all_years_df.drop(columns="Unnamed: 0", inplace=True)

In [89]:
all_years_df

,Country,Happiness Score,GDP per Capita,Social Support,Health/Life Expectancy,Freedom to Make Choices,Generosity,Perceptions of Gov’t Corruption,Year
0,Denmark,7.5260,1.441780,1.163740,0.795040,0.579410,0.361710,0.444530,2016
1,Switzerland,7.5090,1.527330,1.145240,0.863030,0.585570,0.280830,0.412030,2016
2,Iceland,7.5010,1.426660,1.183260,0.867330,0.566240,0.476780,0.149750,2016
3,Norway,7.4980,1.577440,1.126900,0.795790,0.596090,0.378950,0.357760,2016
4,Finland,7.4130,1.405980,1.134640,0.810910,0.571040,0.254920,0.410040,2016
...,...,...,...,...,...,...,...,...,...
148,Central African Republic,3.4759,6.625160,0.319460,45.200001,0.640881,0.082410,0.891807,2020
149,Rwanda,3.3123,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,2020
150,Zimbabwe,3.2992,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,2020
151,South Sudan,2.8166,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,2020
152,Afghanistan,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,2020

In [90]:
us_df = all_years_df.loc[all_years_df["Country"] == "United States"]
us_df

,Country,Happiness Score,GDP per Capita,Social Support,Health/Life Expectancy,Freedom to Make Choices,Generosity,Perceptions of Gov’t Corruption,Year
12,United States,7.1040,1.507960,1.047820,0.779000,0.481630,0.410770,0.148680,2016
13,United States,6.9930,1.546259,1.419921,0.774287,0.505741,0.392579,0.135639,2017
17,United States,6.8860,1.398000,1.471000,0.819000,0.547000,0.291000,0.133000,2018
18,United States,6.8920,1.433000,1.457000,0.874000,0.454000,0.280000,0.128000,2019
17,United States,6.9396,10.925769,0.914219,68.299500,0.842620,0.149892,0.699715,2020

In [91]:
counts = all_years_df["Country"].value_counts()
clean_all_years_df = all_years_df[~all_years_df["Country"].isin(counts[counts < 5].index)]

In [92]:
clean_all_years_df

,Country,Happiness Score,GDP per Capita,Social Support,Health/Life Expectancy,Freedom to Make Choices,Generosity,Perceptions of Gov’t Corruption,Year
0,Denmark,7.5260,1.441780,1.163740,0.795040,0.579410,0.361710,0.444530,2016
1,Switzerland,7.5090,1.527330,1.145240,0.863030,0.585570,0.280830,0.412030,2016
2,Iceland,7.5010,1.426660,1.183260,0.867330,0.566240,0.476780,0.149750,2016
3,Norway,7.4980,1.577440,1.126900,0.795790,0.596090,0.378950,0.357760,2016
4,Finland,7.4130,1.405980,1.134640,0.810910,0.571040,0.254920,0.410040,2016
...,...,...,...,...,...,...,...,...,...
147,Tanzania,3.4762,7.967665,0.688933,57.496075,0.821540,0.109669,0.619799,2020
149,Rwanda,3.3123,7.600104,0.540835,61.098846,0.900589,0.055484,0.183541,2020
150,Zimbabwe,3.2992,7.865712,0.763093,55.617260,0.711458,-0.072064,0.810237,2020
151,South Sudan,2.8166,7.425360,0.553707,51.000000,0.451314,0.016519,0.763417,2020
152,Afghanistan,2.5669,7.462861,0.470367,52.590000,0.396573,-0.096429,0.933687,2020

In [93]:
clean_all_years_df.to_csv("../Resources/clean_data_all_years.csv")